import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';

@Injectable()

export class DataService {

  private projectsList = new BehaviorSubject<any>(
    [
      {
        'id': 1,
        'name': 'Virtual Self-Driving Car',
        'description': "Implementation of a simple virtual self-driving car using Udacity's self-driving car simulator. The model for the car is built using Keras, and it is trained on data that I generated by manually driving a virtual car using Udacity's simulator. It uses a Convolutional Neural Network that takes as its input the pixels from the simulator screen and decides what to do next based on its current state in the world.",
        'githubLink': '',
        'tags': [
          'Keras', 'Deep Learning'
        ]
      },
      {
        'id': 2,
        'name': 'Distributed Exchange Smart Contract',
        'description': "Currently working on a Solidity smart contract implementing a simple distributed exchange for ERC20 tokens on the Ethereum blockchain. It will contain basic functionality such as placing a buy or sell order and depositing or withdrawing tokens.",
        'githubLink': '',
        'tags': [
          'Solidity', 'Truffle'
        ]
      },
      {
        'id': 3,
        'name': 'Politizar',
        'description': "Web app built using Rails where Brazilian voters can subscribe to weekly emails with updates regarding what their state representatives have done during that week. Includes information such as votes, absences, projects, and news. Hoping to get it out in the wild before the presidential elections this year.",
        'githubLink': '',
        'tags': [
          'Ruby on Rails'
        ]
      },

      {
        'id': 4,
        'name': 'Papramaki',
        'description': "Android application built during my Software Development class that tracks users' spending habits. I played the role of project manager leading our team to deliver functionalities beyond the initial expectations for the project. I also built the Ruby on Rails API consumed by the Android app.",
        'githubLink': '',
        'tags': [
          'Android', 'Java', 'Ruby on Rails'
        ]
      },
      {
        'id': 5,
        'name': 'BlindSight',
        'description': "Project for Intel Singapore Invent 50 Competition, where our team built glasses that use Intel's Real Sense Camera to help people who are visually impaired make sense of their environment. I implemented text reading and object recognition features in C++. We were chosen as finalists at the competition.",
        'githubLink': '',
        'tags': [
          'C++', 'Computer Vision'
        ]
      },
      {
        'id': 6,
        'name': 'S.O.P.H.I.E.',
        'description': 'S.O.P.H.I.E. is an underwater robot I built with 2 other Macalester students for our AI Robotics class. It has a Raspberry Pi as its "brain" and it can be controlled using an API built using Python. S.O.P.H.I.E. is now part of the Macalester robotics lab, where other students can do future work on improving it.',
        'githubLink': '',
        'tags': [
          'AI', 'Robotics', 'Python'
        ]
      }
    ]
  );
  projects = this.projectsList.asObservable();

  private coursesList = new BehaviorSubject<any>(
    [
      {
        'id': 1,
        'name': 'Deep Learning Foundations Nanodegree',
        'url': 'https://www.udacity.com/course/deep-learning-nanodegree--nd101',
        'description': 'In this nanodegree, I built a neural network from scratch as well as more advanced models with convolutional, generative adversarial and recurrent neural networks using TensorFlow. Check out my GitHub profile for more details.',
        'tags': [
          'Udacity'
        ]
      },
      {
        'id': 2,
        'name': 'Machine Learning Engineer Nanodegree',
        'url': 'https://www.udacity.com/course/machine-learning-engineer-nanodegree--nd009t',
        'description': 'Currently working on this nanodegree. Stay tuned for updates.',
        'tags': [
          'Udacity'
        ]
      }
    ]
  );
  courses = this.coursesList.asObservable();

  constructor() { }

}
