import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';

@Injectable()

export class DataService {

  private projectsList = new BehaviorSubject<any>(
    [
      {
        'id': 1,
        'name': 'Fresh Eyes',
        'description': 'Chrome extension that adds an accessibility function for users with color blindness. It adapts the color of individual pixels on the browser screen depending on the specific type of color blindness a user has, making it easier to visualize content and navigate the web.',
        'githubLink': '',
        'displayOnHome': false,
        'tags': [
          'JavaScript', 'Chrome Extension'
        ]
      },
      {
        'id': 2,
        'name': 'BlindSight',
        'description': "Project for Intel Singapore Invent 50 Competition, where our team built glasses that use Intel's Real Sense Camera to help people who are visually impaired make sense of their environment. I implemented text reading and object recognition features in C++. We were chosen as finalists at the competition.",
        'githubLink': '',
        'displayOnHome': false,
        'tags': [
          'C++', 'Computer Vision'
        ]
      },
      {
        'id': 3,
        'name': 'Papramaki',
        'description': "Android application built during my Software Development class that tracks users' spending habits. I played the role of project manager leading our team to deliver functionalities beyond the initial expectations for the project. I also built the Ruby on Rails API consumed by the Android app.",
        'githubLink': '',
        'displayOnHome': false,
        'tags': [
          'Android', 'Java', 'Ruby on Rails', 'API'
        ]
      },
      {
        'id': 4,
        'name': 'S.O.P.H.I.E.',
        'description': 'S.O.P.H.I.E. is an underwater robot I built with 2 other Macalester students for our AI Robotics class. It has a Raspberry Pi as its "brain" and it can be controlled using an API built using Python. S.O.P.H.I.E. is now part of the Macalester robotics lab, where other students can do future work on improving it.',
        'githubLink': '',
        'displayOnHome': false,
        'tags': [
          'AI', 'Robotics', 'Python'
        ]
      },
      {
        'id': 5,
        'name': 'Politizar',
        'description': "Web app built using Rails where Brazilian voters can subscribe to weekly emails with updates regarding what their state representatives have done during that week. Includes information such as votes, absences, projects, and news. Hoping to get it out in the wild before the presidential elections this year.",
        'githubLink': '',
        'displayOnHome': true,
        'tags': [
          'Ruby on Rails'
        ]
      },
      {
        'id': 6,
        'name': 'Face Generation',
        'description': "As the final assignment for Udacity’s Deep Learning Foundations Nanodegree, I used a general adversarial network built in Tensorflow to generate realistic faces based on a dataset of celebrity photos.",
        'githubLink': '',
        'displayOnHome': false,
        'tags': [
          'Ruby on Rails'
        ]
      },
      {
        'id': 7,
        'name': 'Pet Shop Smart Contract',
        'description': "Smart contract for adopting pets from a fake virtual pet shop. A very simple user interface allows users to see a list of pets and adopt the ones they like, deducting Ether from their balance.",
        'githubLink': '',
        'displayOnHome': false,
        'tags': [
          'Solidity', 'Truffle'
        ]
      },
      {
        'id': 8,
        'name': 'ERC-20 Token Smart Contract',
        'description': "Implemented a simple ERC20 token using the Truffle framework. The code is based off of the Standard Token implemented by the OpenZeppelin library as a framework for building secure smart contracts on Ethereum.",
        'githubLink': '',
        'displayOnHome': false,
        'tags': [
          'Solidity', 'Truffle'
        ]
      },
      {
        'id': 9,
        'name': 'Distributed Exchange Smart Contract',
        'description': "Currently working on a Solidity smart contract implementing a simple distributed exchange for ERC20 tokens on the Ethereum blockchain. It will contain basic functionality such as placing a buy or sell order and depositing or withdrawing tokens.",
        'githubLink': '',
        'displayOnHome': true,
        'tags': [
          'Solidity', 'Truffle'
        ]
      },
      {
        'id': 10,
        'name': 'Virtual Self-Driving Car',
        'description': "Implementation of a simple virtual self-driving car using Udacity's self-driving car simulator. The model for the car is built using Keras, and it is trained on data that I generated by manually driving a virtual car using Udacity's simulator. It uses a Convolutional Neural Network that takes as its input the pixels from the simulator screen and decides what to do next based on its current state in the world.",
        'githubLink': '',
        'displayOnHome': true,
        'tags': [
          'Keras', 'Deep Learning'
        ]
      }
    ]
  );
  projects = this.projectsList.asObservable();

  private coursesList = new BehaviorSubject<any>(
    [
      {
        'id': 1,
        'name': 'Deep Learning Foundations Nanodegree',
        'url': 'https://www.udacity.com/course/deep-learning-nanodegree--nd101',
        'description': 'In this nanodegree, I built a neural network from scratch as well as more advanced models with convolutional, generative adversarial and recurrent neural networks using TensorFlow. Check out my GitHub profile for more details.',
        'tags': [
          'Udacity'
        ]
      },
      {
        'id': 2,
        'name': 'Machine Learning Engineer Nanodegree',
        'url': 'https://www.udacity.com/course/machine-learning-engineer-nanodegree--nd009t',
        'description': 'Currently working on this nanodegree. Stay tuned for updates.',
        'tags': [
          'Udacity'
        ]
      }
    ]
  );
  courses = this.coursesList.asObservable();

  constructor() { }

}
